export const BOOKING_ROOM_REQUEST="BOOKING_ROOM_REQUEST"
export const BOOKING_ROOM_SUCCESS="BOOKING_ROOM_SUCCESS"
export const BOOKING_ROOM_FAIL="BOOKING_ROOM_FAIL"

export const CANCEL_BOOKING_REQUEST="CANCEL_BOOKING_REQUEST"
export const CANCEL_BOOKING_SUCCESS="CANCEL_BOOKING_SUCCESS"
export const CANCEL_BOOKING_FAIL="CANCEL_BOOKING_FAIL"


export const GET_USER_BOOKINGS_REQUEST="GET_USER_BOOKINGS_REQUEST"
export const GET_USER_BOOKINGS_SUCCESS="GET_USER_BOOKINGS_SUCCESS"
export const GET_USER_BOOKINGS_FAIL="GET_USER_BOOKINGS_FAIL"