export const GET_ALL_ROOMS_REQUEST="GET_ALL_ROOMS_REQUEST";
export const GET_ALL_ROOMS_SUCCESS="GET_ALL_ROOMS_SUCCESS";
export const GET_ALL_ROOMS_FAIL="GET_ALL_ROOMS_FAIL";

export const GET_ROOM_BY_ID_REQUEST="GET_ROOM_BY_ID_REQUEST";
export const GET_ROOM_BY_ID_SUCCESS="GET_ROOM_BY_ID_SUCCESS";
export const GET_ROOM_BY_ID_FAIL="GET_ROOM_BY_ID_FAIL";
